import { useEffect, useMemo, useRef, useState } from 'react';
import { useRouter } from 'next/router';
import { createQuote, estimateQuote } from '@/api/logistics';
import { useBackendAuth } from '@/auth/useBackendAuth';

const DRAFT_KEY = 'diaexpress.quote.smartDraft.v2';
const steps = ['Origine', 'Transport', 'Envoi', 'Colis', 'Services', 'Contacts', 'Résumé'];
const transportModes = [
  { id: 'air', label: 'Air', icon: '✈️', hint: 'Rapide, poids prioritaire', eta: '2–5 jours' },
  { id: 'sea', label: 'Maritime', icon: '🚢', hint: 'Volume et conteneurs', eta: '15–35 jours' },
  { id: 'road', label: 'Routier', icon: '🚚', hint: 'Régional, flexible', eta: '1–7 jours' },
  { id: 'express', label: 'Express', icon: '⚡', hint: 'Urgent, suivi renforcé', eta: '24–72h' },
];
const shipmentTypes = ['Document', 'Colis', 'Marchandise', 'Palette', 'Conteneur', 'Autre'];
const services = [
  ['insurance', 'Assurance', 'Protège la valeur déclarée.'],
  ['urgent', 'Livraison urgente', 'Priorise le traitement opérationnel.'],
  ['pickup', 'Collecte à domicile', 'Nous organisons l’enlèvement.'],
  ['homeDelivery', 'Livraison à domicile', 'Adresse finale détaillée utile.'],
  ['fragile', 'Fragile', 'Prévoit une manipulation adaptée.'],
];
const initialDraft = {
  origin: { country: '', city: '', address: '' },
  destination: { country: '', city: '', address: '' },
  transportType: '', shipmentType: '', weight: '', length: '', width: '', height: '', declaredValue: '', services: {},
  sender: { name: '', phone: '', email: '' }, recipient: { name: '', phone: '', email: '' },
};
const num = (v) => Number.parseFloat(v || '0') || 0;
const round = (v, d = 2) => Number.isFinite(v) ? Number(v.toFixed(d)) : 0;
const hasDims = (d) => num(d.length) > 0 && num(d.width) > 0 && num(d.height) > 0;
const calc = (d) => {
  const volume = hasDims(d) ? round((num(d.length) * num(d.width) * num(d.height)) / 1000000, 3) : 0;
  const volumetricWeight = hasDims(d) ? round((num(d.length) * num(d.width) * num(d.height)) / (d.transportType === 'road' ? 4000 : 5000), 2) : 0;
  const taxableWeight = round(Math.max(num(d.weight), volumetricWeight), 2);
  return { volume, volumetricWeight, taxableWeight };
};
const money = (amount, currency = 'USD') => Number.isFinite(Number(amount)) ? new Intl.NumberFormat('fr-FR', { style: 'currency', currency }).format(Number(amount)) : '—';
const clean = (v) => String(v || '').trim();
const isEmail = (v) => !v || /.+@.+\..+/.test(v);

export function QuoteProgress({ step, setStep }) {
  return <ol className="quote-progress">{steps.map((label, index) => <li key={label} className={index === step ? 'is-active' : index < step ? 'is-done' : ''}><button type="button" onClick={() => setStep(index)}><span>{index + 1}</span>{label}</button></li>)}</ol>;
}
export function QuotePriceCard({ estimate, status, metrics }) {
  return <article className="quote-price-card"><p className="dx-kicker">estimation temps réel</p><strong>{estimate?.price ? money(estimate.price, estimate.currency) : 'À calculer'}</strong><span>{estimate?.eta || 'Délai affiché dès que la route, le transport et le colis sont suffisants.'}</span><small>{status === 'loading' ? 'Calcul en cours…' : status === 'error' ? 'Tarif indicatif local affiché si le moteur est indisponible.' : `${metrics.taxableWeight || 0} kg taxables`}</small></article>;
}
export function QuoteSummaryCard({ draft, estimate, estimateStatus }) {
  const metrics = calc(draft);
  const mode = transportModes.find((m) => m.id === draft.transportType);
  return <aside className="quote-summary-card"><h2>Résumé permanent</h2><p className="quote-route">{draft.origin.city || 'Origine'} → {draft.destination.city || 'Destination'}</p><dl><dt>Transport</dt><dd>{mode?.label || '—'}</dd><dt>Poids</dt><dd>{draft.weight || '—'} kg</dd><dt>Volume</dt><dd>{metrics.volume || '—'} m³</dd><dt>Prix</dt><dd>{estimate?.price ? money(estimate.price, estimate.currency) : '—'}</dd><dt>Délai</dt><dd>{estimate?.eta || mode?.eta || '—'}</dd></dl><QuotePriceCard estimate={estimate} status={estimateStatus} metrics={metrics} /></aside>;
}
function Field({ label, why, children }) { return <label className="quote-field"><span>{label}</span>{children}{why ? <small>Pourquoi ? {why}</small> : null}</label>; }
function patchNested(setDraft, key, sub, value) { setDraft((d) => ({ ...d, [key]: { ...d[key], [sub]: value } })); }
export function QuoteStepLocation({ draft, setDraft }) { return <section className="quote-step"><h2>Origine et destination</h2><div className="quote-grid two"><div><h3>Origine</h3><Field label="Pays"><input value={draft.origin.country} onChange={(e)=>patchNested(setDraft,'origin','country',e.target.value)} /></Field><Field label="Ville"><input value={draft.origin.city} onChange={(e)=>patchNested(setDraft,'origin','city',e.target.value)} /></Field><Field label="Adresse optionnelle" why="Elle accélère la collecte, mais ne bloque pas le devis."><input value={draft.origin.address} onChange={(e)=>patchNested(setDraft,'origin','address',e.target.value)} /></Field></div><div><h3>Destination</h3><Field label="Pays"><input value={draft.destination.country} onChange={(e)=>patchNested(setDraft,'destination','country',e.target.value)} /></Field><Field label="Ville"><input value={draft.destination.city} onChange={(e)=>patchNested(setDraft,'destination','city',e.target.value)} /></Field><Field label="Adresse optionnelle"><input value={draft.destination.address} onChange={(e)=>patchNested(setDraft,'destination','address',e.target.value)} /></Field></div></div><p className="quote-detected-route">Route détectée : {draft.origin.city || '—'}, {draft.origin.country || '—'} → {draft.destination.city || '—'}, {draft.destination.country || '—'}</p></section>; }
export function QuoteStepTransport({ draft, setDraft }) { return <section className="quote-step"><h2>Type transport</h2><div className="quote-choice-grid">{transportModes.map((m) => <button className={draft.transportType === m.id ? 'selected' : ''} type="button" key={m.id} onClick={() => setDraft((d)=>({ ...d, transportType: m.id }))}><b>{m.icon} {m.label}</b><span>{m.hint}</span><small>{m.eta}</small></button>)}</div><p className="quote-helper">Le choix adapte les validations : Air privilégie le poids, Maritime privilégie les dimensions/volume.</p></section>; }
export function QuoteStepPackage({ draft, setDraft, mode }) { const metrics = calc(draft); const maritime = draft.transportType === 'sea'; return <section className="quote-step"><h2>{mode === 'type' ? 'Type d’envoi' : 'Informations colis'}</h2>{mode === 'type' ? <div className="quote-choice-grid">{shipmentTypes.map((type)=><button type="button" key={type} className={draft.shipmentType === type ? 'selected' : ''} onClick={()=>setDraft((d)=>({ ...d, shipmentType:type }))}>{type}</button>)}</div> : <><div className="quote-grid two"><Field label={`Poids (kg)${maritime ? ' — secondaire' : ''}`} why="Il sert à calculer le poids taxable."><input type="number" min="0" value={draft.weight} onChange={(e)=>setDraft((d)=>({ ...d, weight:e.target.value }))} /></Field><Field label="Valeur déclarée" why="Elle permet de proposer l’assurance sans ralentir la demande."><input type="number" min="0" value={draft.declaredValue} onChange={(e)=>setDraft((d)=>({ ...d, declaredValue:e.target.value }))} /></Field></div><div className="quote-grid three"><Field label={`Longueur cm${maritime ? ' *' : ''}`}><input type="number" min="0" value={draft.length} onChange={(e)=>setDraft((d)=>({ ...d, length:e.target.value }))} /></Field><Field label={`Largeur cm${maritime ? ' *' : ''}`}><input type="number" min="0" value={draft.width} onChange={(e)=>setDraft((d)=>({ ...d, width:e.target.value }))} /></Field><Field label={`Hauteur cm${maritime ? ' *' : ''}`}><input type="number" min="0" value={draft.height} onChange={(e)=>setDraft((d)=>({ ...d, height:e.target.value }))} /></Field></div><div className="quote-metrics"><span>Volume {metrics.volume} m³</span><span>Poids volumétrique {metrics.volumetricWeight} kg</span><span>Poids taxable {metrics.taxableWeight} kg</span></div></>}</section>; }
export function QuoteStepServices({ draft, setDraft }) { return <section className="quote-step"><h2>Services complémentaires</h2><div className="quote-choice-grid">{services.map(([id,label,hint])=><button type="button" key={id} className={draft.services[id] ? 'selected' : ''} onClick={()=>setDraft((d)=>({ ...d, services:{...d.services,[id]:!d.services[id]} }))}><b>{label}</b><span>{hint}</span></button>)}</div></section>; }
export function QuoteStepContacts({ draft, setDraft }) { return <section className="quote-step"><h2>Informations contact</h2><div className="quote-grid two"><div><h3>Expéditeur</h3>{['name','phone','email'].map((k)=><Field key={k} label={k === 'name' ? 'Nom' : k === 'phone' ? 'Téléphone' : 'Email'}><input type={k==='email'?'email':'text'} value={draft.sender[k]} onChange={(e)=>patchNested(setDraft,'sender',k,e.target.value)} /></Field>)}</div><div><h3>Destinataire</h3>{['name','phone','email'].map((k)=><Field key={k} label={k === 'name' ? 'Nom' : k === 'phone' ? 'Téléphone' : 'Email'}><input type={k==='email'?'email':'text'} value={draft.recipient[k]} onChange={(e)=>patchNested(setDraft,'recipient',k,e.target.value)} /></Field>)}</div></div></section>; }
export function QuoteStepReview({ draft, estimate }) { const metrics = calc(draft); const activeServices = services.filter(([id])=>draft.services[id]).map(([,label])=>label); return <section className="quote-step"><h2>Résumé</h2><dl className="quote-review"><dt>Origine</dt><dd>{draft.origin.city}, {draft.origin.country}</dd><dt>Destination</dt><dd>{draft.destination.city}, {draft.destination.country}</dd><dt>Transport</dt><dd>{draft.transportType}</dd><dt>Poids / volume</dt><dd>{draft.weight || '—'} kg · {metrics.volume || '—'} m³</dd><dt>Services</dt><dd>{activeServices.join(', ') || 'Aucun'}</dd><dt>Prix estimé</dt><dd>{estimate?.price ? money(estimate.price, estimate.currency) : '—'}</dd><dt>Délai estimé</dt><dd>{estimate?.eta || '—'}</dd></dl></section>; }

const canEstimate = (d) => clean(d.origin.country) && clean(d.destination.country) && clean(d.origin.city) && clean(d.destination.city) && clean(d.transportType) && (num(d.weight) > 0 || hasDims(d));
const buildPayload = (d, estimate) => { const metrics = calc(d); return { origin: `${clean(d.origin.city)}, ${clean(d.origin.country)}`, destination: `${clean(d.destination.city)}, ${clean(d.destination.country)}`, originCountry: clean(d.origin.country), originCity: clean(d.origin.city), originAddress: clean(d.origin.address), destinationCountry: clean(d.destination.country), destinationCity: clean(d.destination.city), destinationAddress: clean(d.destination.address), transportType: d.transportType, packageTypeId: d.shipmentType, shipmentType: d.shipmentType, weight: num(d.weight) || undefined, length: num(d.length) || undefined, width: num(d.width) || undefined, height: num(d.height) || undefined, volume: metrics.volume || undefined, declaredValue: num(d.declaredValue) || undefined, services: Object.keys(d.services).filter((k)=>d.services[k]), sender: d.sender, recipient: d.recipient, contactName: d.sender.name, contactPhone: d.sender.phone, contactEmail: d.sender.email, estimatedPrice: estimate?.price, currency: estimate?.currency || 'USD', status: 'submitted' }; };
const fallbackEstimate = (d) => { const metrics = calc(d); const base = d.transportType === 'express' ? 45 : d.transportType === 'air' ? 30 : d.transportType === 'sea' ? 18 : 15; const multiplier = Math.max(metrics.taxableWeight || num(d.weight) || metrics.volume * 250 || 1, 1); const serviceFee = Object.values(d.services).filter(Boolean).length * 8; return { price: round(base + multiplier * (d.transportType === 'sea' ? 4 : 6) + serviceFee, 2), currency: 'USD', eta: transportModes.find((m)=>m.id===d.transportType)?.eta || 'À confirmer' }; };
export default function QuoteWizard() {
  const router = useRouter(); const { isSignedIn, getToken } = useBackendAuth(); const [step, setStep] = useState(0); const [draft, setDraft] = useState(initialDraft); const [estimate, setEstimate] = useState(null); const [estimateStatus, setEstimateStatus] = useState('idle'); const [submitStatus, setSubmitStatus] = useState('idle'); const sigRef = useRef('');
  useEffect(()=>{ try { const saved = JSON.parse(localStorage.getItem(DRAFT_KEY) || 'null'); if (saved) setDraft({ ...initialDraft, ...saved }); } catch {} }, []);
  useEffect(()=>{ localStorage.setItem(DRAFT_KEY, JSON.stringify(draft)); }, [draft]);
  useEffect(()=>{ const sig = JSON.stringify({ o:draft.origin, de:draft.destination, t:draft.transportType, w:draft.weight, l:draft.length, wi:draft.width, h:draft.height, s:draft.services }); if (!canEstimate(draft) || sig === sigRef.current) return; sigRef.current = sig; let alive = true; setEstimateStatus('loading'); const local = fallbackEstimate(draft); estimateQuote(buildPayload(draft, local)).then((res)=>{ if(!alive) return; const price = Number(res?.estimatedPrice ?? res?.price ?? res?.data?.estimatedPrice ?? local.price); setEstimate({ price: Number.isFinite(price) ? price : local.price, currency: res?.currency || res?.data?.currency || local.currency, eta: res?.eta || res?.estimatedDelay || local.eta }); setEstimateStatus('success'); }).catch(()=>{ if(alive){ setEstimate(local); setEstimateStatus('error'); } }); return ()=>{ alive=false; }; }, [draft]);
  const validation = useMemo(()=>{ const errors = []; if (step >= 0 && (!clean(draft.origin.country) || !clean(draft.origin.city) || !clean(draft.destination.country) || !clean(draft.destination.city))) errors.push('Route incomplète.'); if (step >= 1 && !draft.transportType) errors.push('Choisissez un transport.'); if (step >= 2 && !draft.shipmentType) errors.push('Choisissez un type d’envoi.'); if (step >= 3) { if (draft.transportType === 'sea' && !hasDims(draft)) errors.push('Dimensions obligatoires en maritime.'); if (draft.transportType !== 'sea' && num(draft.weight) <= 0) errors.push('Poids obligatoire pour ce transport.'); } if (step >= 5) { if (!clean(draft.sender.name) || !clean(draft.sender.phone) || !clean(draft.sender.email)) errors.push('Contact expéditeur incomplet.'); if (!clean(draft.recipient.name) || !clean(draft.recipient.phone) || !clean(draft.recipient.email)) errors.push('Contact destinataire incomplet.'); if (!isEmail(draft.sender.email) || !isEmail(draft.recipient.email)) errors.push('Email invalide.'); } return errors; }, [draft, step]);
  const Step = [QuoteStepLocation, QuoteStepTransport, (p)=><QuoteStepPackage {...p} mode="type" />, QuoteStepPackage, QuoteStepServices, QuoteStepContacts, QuoteStepReview][step];
  const submit = async () => { if (validation.length) return; if (!isSignedIn) { router.push(`/sign-in?returnUrl=${encodeURIComponent('/quote-request')}`); return; } setSubmitStatus('loading'); try { const token = await getToken(); const res = await createQuote(buildPayload(draft, estimate || fallbackEstimate(draft)), token); localStorage.removeItem(DRAFT_KEY); const id = res?.quote?._id || res?._id || res?.quoteId; router.push(id ? `/quote-request/success?quoteId=${encodeURIComponent(id)}` : '/quote-request/success'); } catch { setSubmitStatus('error'); } };
  return <main className="quote-wizard-page"><div className="quote-wizard-shell"><header className="quote-wizard-hero"><p className="dx-kicker">DiaExpress · devis intelligent</p><h1>Demandez un devis logistique en moins de 3 minutes</h1><p>Un flow mobile-first, sauvegardé automatiquement, avec estimation dès que les données métier sont suffisantes.</p></header><QuoteProgress step={step} setStep={setStep} /><div className="quote-wizard-layout"><div className="quote-wizard-card"><Step draft={draft} setDraft={setDraft} estimate={estimate} /><div className="quote-errors">{validation.slice(0,2).map((e)=><p key={e}>{e}</p>)}</div><div className="quote-nav"><button type="button" disabled={step===0} onClick={()=>setStep((s)=>Math.max(0,s-1))}>Retour</button>{step < 6 ? <button type="button" onClick={()=>setStep((s)=>Math.min(6,s+1))}>Continuer</button> : <button type="button" disabled={submitStatus==='loading' || validation.length > 0} onClick={submit}>{submitStatus==='loading' ? 'Envoi…' : 'Demander le devis'}</button>}</div>{submitStatus==='error' ? <p className="quote-error">Soumission impossible pour le moment. Votre brouillon reste sauvegardé.</p> : null}</div><QuoteSummaryCard draft={draft} estimate={estimate} estimateStatus={estimateStatus} /></div></div></main>;
}
