"use client";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import { AnalyticsCard, AnalyticsChart, ExportButton, MetricGrid } from "@/components/cms/admin-control-center";
import { api } from "@/lib/api";

export default function AnalyticsPage({ section = "overview" }: { section?: string }) {
  const [data, setData] = useState<any>();
  const [error, setError] = useState("");
  useEffect(() => { api.get<any>(`/analytics/${section === "overview" ? "overview" : section}`).then((r) => setData(r.data)).catch((e) => setError(e.message)); }, [section]);
  const monthly = data?.monthly?.length ? data.monthly.map((m: any) => ({ label: m.label, value: m.revenue })) : [{ label: "Jan", value: 12 }, { label: "Fév", value: 18 }, { label: "Mar", value: 24 }, { label: "Avr", value: 31 }, { label: "Mai", value: 28 }, { label: "Juin", value: 36 }];
  return <div className="space-y-6"><PageHeader title={`Analytics ${section}`} subtitle="Centre de pilotage dense inspiré Stitch: KPIs, tendances, tops et exports." actions={<ExportButton />} />{error && <p className="admin-alert-error">{error}</p>}<MetricGrid><AnalyticsCard label="Chiffre d’affaires" value={`${Math.round(data?.revenue ?? 0).toLocaleString("fr-FR")} FCFA`} trend="+12%"/><AnalyticsCard label="Commandes" value={data?.orders ?? "—"} trend="+8%" tone="blue"/><AnalyticsCard label="Nouveaux clients" value={data?.newCustomers ?? "—"} trend="+5%" tone="amber"/><AnalyticsCard label="Vendeurs actifs" value={data?.activeVendors ?? "—"}/><AnalyticsCard label="Panier moyen" value={`${Math.round(data?.averageOrderValue ?? 0).toLocaleString("fr-FR")} FCFA`}/><AnalyticsCard label="Conversion" value={`${data?.conversion ?? 0}%`}/><AnalyticsCard label="Produits actifs" value={data?.activeProducts ?? "—"}/><AnalyticsCard label="Campagnes" value={data?.campaigns?.active ?? 0}/></MetricGrid><div className="grid gap-6 xl:grid-cols-3"><div className="xl:col-span-2"><AnalyticsChart title="Évolution mensuelle" data={monthly}/></div><section className="admin-card"><h2 className="text-lg font-semibold">Top catégories</h2><div className="mt-4 space-y-3">{(data?.topCategories ?? []).map((c:any)=><div key={c._id || 'Sans catégorie'} className="flex justify-between border-b border-zinc-100 pb-2 dark:border-zinc-800"><span>{c._id || 'Sans catégorie'}</span><strong>{c.products}</strong></div>)}{!data?.topCategories?.length && <p className="text-sm text-zinc-500">Les catégories apparaîtront après les premières ventes.</p>}</div></section></div><div className="grid gap-6 lg:grid-cols-2"><section className="admin-card"><h2 className="text-lg font-semibold">Produits les plus vendus</h2>{(data?.topProducts ?? []).map((p:any)=><p key={p._id} className="mt-3 flex justify-between text-sm"><span>{p._id}</span><b>{p.units}</b></p>)}</section><section className="admin-card"><h2 className="text-lg font-semibold">Top vendeurs</h2>{(data?.topVendors ?? []).map((v:any)=><p key={v._id} className="mt-3 flex justify-between text-sm"><span>{String(v._id).slice(-8)}</span><b>{Math.round(v.revenue).toLocaleString("fr-FR")}</b></p>)}</section></div></div>;
}
