"use client";
import Link from "next/link";
import type { OrderAdminItem, ProductItem, VendorAdminItem, VendorDetailResponse } from "@/types/cms";
const money=(v?:number,c="FCFA")=>`${Math.round(v??0).toLocaleString("fr-FR")} ${c}`; const pct=(v?:number)=>`${Math.round((v??0)*100)}%`;
export function VendorStatCard({label,value,hint}:{label:string;value:string|number;hint?:string}){return <div className="rounded-2xl border bg-white/80 p-4 shadow-sm dark:border-zinc-800 dark:bg-zinc-950"><p className="text-xs uppercase tracking-[.18em] text-zinc-500">{label}</p><strong className="mt-2 block text-2xl">{value}</strong>{hint&&<p className="mt-1 text-xs text-zinc-500">{hint}</p>}</div>}
export function VendorOverviewCard({detail}:{detail:VendorDetailResponse}){const v=detail.vendor;return <section className="overflow-hidden rounded-3xl border bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-950"><div className="h-36 bg-[linear-gradient(135deg,#1f2a1d,#d6b56d,#faf8f3)]"/><div className="grid gap-4 p-5 md:grid-cols-[160px_1fr_260px]"><div className="-mt-16 flex h-32 w-32 items-center justify-center rounded-3xl border-4 border-white bg-olive-700 text-4xl font-bold text-white shadow-xl">{(v.shopName||"V").slice(0,1)}</div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-bold">{v.shopName||"Boutique vendeur"}</h2><span className="rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-700">{v.status}</span></div><p className="mt-1 text-sm text-zinc-500">Storefront /vendors/{v._id} · domaine préparé · {v.country||"Pays à compléter"} · devise FCFA</p><div className="mt-4 grid gap-2 text-sm md:grid-cols-4"><span>⭐ 4,8 notation</span><span>Ancienneté {v.createdAt?new Date(v.createdAt).toLocaleDateString("fr-FR"):"—"}</span><span>{v.city||"Ville —"}</span><span>Commission {pct(v.commissionRate)}</span></div></div><div className="rounded-2xl bg-zinc-950 p-4 text-white"><p className="text-xs text-zinc-400">Boutique</p><p className="font-semibold">Prête Shopify-like</p><p className="mt-3 text-xs text-zinc-400">Actions rapides</p><div className="mt-2 flex flex-wrap gap-2"><Link className="rounded-full bg-white px-3 py-1 text-xs text-zinc-950" href={`/storefront/${v._id}/builder`}>Storefront</Link><Link className="rounded-full border border-white/30 px-3 py-1 text-xs" href={`/vendors/${v._id}/settings`}>Réglages</Link></div></div></div></section>}
export function VendorProfileCard({vendor}:{vendor:VendorAdminItem}){const rows=["Logo","Bannière","Description","Contacts","Horaires","Réseaux sociaux","Adresse","Documents KYC","Informations légales","TVA","IBAN","Mobile Money","Crypto Wallet"];return <section className="rounded-3xl border p-5 dark:border-zinc-800"><h3 className="text-lg font-semibold">Profil vendeur & conformité</h3><p className="text-sm text-zinc-500">Préparé pour Diapay, KYC et moyens de retrait.</p><div className="mt-4 grid gap-3 md:grid-cols-3">{rows.map(x=><div key={x} className="rounded-2xl border bg-zinc-50 p-3 text-sm dark:border-zinc-800 dark:bg-zinc-900"><span className="font-medium">{x}</span><p className="text-xs text-zinc-500">{vendor.shopName||"Vendeur"} · architecture prête</p></div>)}</div></section>}
export function VendorAnalyticsChart({stats}:{stats:VendorDetailResponse["stats"]}){const vals=[stats.revenue,stats.averageOrderValue,stats.pendingOrders*1000,stats.deliveredOrders*1000,stats.estimatedCommission];const max=Math.max(...vals,1);return <div className="rounded-3xl border p-5 dark:border-zinc-800"><h3 className="font-semibold">Analytics vendeur</h3><div className="mt-5 flex h-48 items-end gap-3">{vals.map((v,i)=><div key={i} className="flex-1 rounded-t-2xl bg-olive-700/80" style={{height:`${Math.max(12,(v/max)*100)}%`}} />)}</div><p className="mt-3 text-xs text-zinc-500">Ventes, revenus, commandes, nouveaux clients, conversion, trafic, panier moyen et pays — couche IA future.</p></div>}
export function VendorWalletCard({detail}:{detail:VendorDetailResponse}){const s=detail.stats;return <section className="grid gap-3 md:grid-cols-4"><VendorStatCard label="Solde disponible" value={money(Math.max(s.revenue-s.estimatedCommission,0))}/><VendorStatCard label="Solde bloqué" value={money(s.pendingOrders*15000)}/><VendorStatCard label="Commissions" value={money(s.estimatedCommission)}/><VendorStatCard label="Paiements attente" value={money(s.pendingOrders*25000)}/></section>}
export function VendorPayoutTable(){const rows=[['Virement bancaire','pending','1 500 FCFA'],['Mobile Money','ready','750 FCFA'],['Crypto','planned','variable']];return <Table title="Payouts" headers={["Méthode","Statut","Frais"]} rows={rows}/>}
export function VendorDocumentGrid(){return <div className="grid gap-3 md:grid-cols-3">{['KYC','Registre commerce','Identité','Certificat','Contrat','Factures'].map(x=><div key={x} className="rounded-2xl border p-4 dark:border-zinc-800"><b>{x}</b><p className="text-sm text-zinc-500">Stockage sécurisé à brancher.</p></div>)}</div>}
export function VendorMessageCenter(){return <section className="rounded-3xl border p-5 dark:border-zinc-800"><h3 className="font-semibold">Messagerie admin ↔ vendeur</h3><div className="mt-4 grid gap-3 md:grid-cols-[280px_1fr]"><aside className="space-y-2">{['Support vendeur','Documents KYC','Payout en attente'].map((x,i)=><div key={x} className="rounded-2xl border p-3 text-sm dark:border-zinc-800"><b>{x}</b><p className="text-xs text-zinc-500">{i===0?'non lu':'lu'} · notifications prêtes</p></div>)}</aside><main className="rounded-2xl bg-zinc-50 p-4 dark:bg-zinc-900"><p className="text-sm text-zinc-500">Recherche, filtres, pièces jointes et websocket-ready.</p><div className="mt-6 rounded-2xl bg-white p-3 shadow-sm dark:bg-zinc-950">Bonjour, votre dossier vendeur est en revue.</div></main></div></section>}
export function VendorTimeline(){return <ol className="space-y-3">{['Création boutique','KYC reçu','Catalogue importé','Premier payout planifié'].map(x=><li key={x} className="rounded-2xl border p-3 text-sm dark:border-zinc-800">• {x}</li>)}</ol>}
function Table({title,headers,rows}:{title:string;headers:string[];rows:(string|number)[][]}){return <section className="overflow-hidden rounded-3xl border dark:border-zinc-800"><h3 className="p-4 font-semibold">{title}</h3><table className="w-full text-sm"><thead className="bg-zinc-50 dark:bg-zinc-900"><tr>{headers.map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t dark:border-zinc-800">{r.map((c,j)=><td key={j} className="p-3">{c}</td>)}</tr>)}</tbody></table></section>}
export function VendorCatalogTable({products}:{products:ProductItem[]}){return <Table title="Catalogue vendeur" headers={["Produit","Statut","Stock","Prix"]} rows={products.map(p=>[p.name,p.status||'—',p.stock,money(p.price,p.currency)])}/>}
export function VendorOrdersTable({orders}:{orders:OrderAdminItem[]}){return <Table title="Commandes vendeur" headers={["Commande","Statut","Paiement","Total"]} rows={orders.map(o=>[o._id.slice(-8),o.status||'—',o.paymentStatus||'—',money(o.totalAmount,o.currency)])}/>}
export function VendorCustomerTable({orders}:{orders:OrderAdminItem[]}){return <Table title="Clients vendeur" headers={["Client","Commandes","Dernier statut"]} rows={orders.slice(0,20).map((o,i)=>[typeof o.customer==='object'?(o.customer.name||o.customer.email||'Client'):`Client ${i+1}`,1,o.status||'—'])}/>}
