"use client";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import { DataTable } from "@/components/ui/data-table";
import { StatusBadge } from "@/components/ui/status-badge";
import { cmsService } from "@/services/cms-service";
import type { SlideItem, SlidePayload } from "@/types/cms";
const empty: SlidePayload = { title: "", subtitle: "", imageUrl: "", ctaUrl: "", isActive: true };
export default function SlidesPage(){const [items,setItems]=useState<SlideItem[]>([]);const [form,setForm]=useState<SlidePayload>(empty);const [editing,setEditing]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [message,setMessage]=useState("");const load=async()=>{setLoading(true);setError("");try{setItems(await cmsService.getSlides())}catch(e){setError((e as Error).message)}finally{setLoading(false)}};useEffect(()=>{void load()},[]);const save=async()=>{if(!form.title.trim()){setError("Le titre est obligatoire.");return}try{editing?await cmsService.updateSlide(editing,form):await cmsService.createSlide(form);setForm(empty);setEditing(null);setMessage("Slide sauvegardé.");await load()}catch(e){setError((e as Error).message)}};const edit=(s:SlideItem)=>{setEditing(String(s._id??s.id));setForm({title:s.title,subtitle:s.subtitle??"",imageUrl:s.imageUrl??"",ctaUrl:s.ctaUrl??s.cta??"",isActive:s.isActive!==false})};const del=async(s:SlideItem)=>{const id=String(s._id??s.id);if(!confirm(`Supprimer ${s.title} ?`))return;try{await cmsService.deleteSlide(id);setMessage("Slide supprimé.");await load()}catch(e){setError((e as Error).message)}};const rows=items.map(s=>({id:String(s._id??s.id),searchableText:`${s.title} ${s.subtitle}`,cells:[s.title,s.subtitle??"—",s.imageUrl??"—",<StatusBadge key="st" status={s.isActive===false?"inactive":"active"}/>,<span key="a" className="flex gap-2"><button className="rounded border px-2 py-1" onClick={()=>edit(s)}>Modifier</button><button className="rounded border px-2 py-1 text-red-700" onClick={()=>del(s)}>Supprimer</button></span>]}));return <div className="space-y-6"><PageHeader title="Slides" subtitle="Slides homepage connectés aux endpoints existants" />{error&&<p className="rounded-xl bg-red-500/10 p-3 text-red-700">{error}</p>}{message&&<p className="rounded-xl bg-blue-500/10 p-3">{message}</p>}<section className="grid gap-3 rounded-2xl border p-4 md:grid-cols-5 dark:border-zinc-800"><input className="rounded-xl border p-2" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Titre"/><input className="rounded-xl border p-2" value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})} placeholder="Sous-titre"/><input className="rounded-xl border p-2" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} placeholder="Image URL"/><label className="flex items-center gap-2"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Actif</label><button onClick={save} className="rounded-md bg-olive-700 px-4 py-2 text-white">{editing?"Mettre à jour":"Créer"}</button></section>{loading?<p>Chargement des slides…</p>:rows.length?<DataTable headers={["Titre","Sous-titre","Image","Statut","Action"]} rows={rows}/>:<p className="rounded-xl border p-4 text-sm text-zinc-500">Aucun slide.</p>}</div>}
