"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { cmsService } from "@/services/cms-service";
import type { VendorDetailResponse } from "@/types/cms";
import { VendorAnalyticsChart, VendorCatalogTable, VendorCustomerTable, VendorDocumentGrid, VendorMessageCenter, VendorOrdersTable, VendorOverviewCard, VendorPayoutTable, VendorProfileCard, VendorStatCard, VendorTimeline, VendorWalletCard } from "@/components/vendors";
const money=(v?:number)=>`${Math.round(v??0).toLocaleString("fr-FR")} FCFA`;
const tabs=["overview","profile","catalog","orders","customers","analytics","payouts","wallet","messaging","documents","settings"];
export default function VendorHubPage({id,section="overview"}:{id:string;section?:string}){const [detail,setDetail]=useState<VendorDetailResponse|null>(null);const [error,setError]=useState("");useEffect(()=>{cmsService.getVendor(id).then(r=>setDetail(r.data)).catch(e=>setError(e instanceof Error?e.message:"Erreur vendeur"))},[id]);if(error)return <p className="rounded-xl bg-red-500/10 p-4 text-red-700">{error}</p>;if(!detail)return <p className="rounded-xl border p-4">Chargement Seller Hub…</p>;const s=detail.stats;return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.22em] text-olive-700">Seller Hub</p><h1 className="text-3xl font-bold">{detail.vendor.shopName}</h1></div><div className="flex flex-wrap gap-2">{tabs.map(t=><Link key={t} className={`rounded-full px-3 py-1 text-sm ${section===t?'bg-zinc-950 text-white':'border'}`} href={`/vendors/${id}/${t}`}>{t}</Link>)}</div></div><VendorOverviewCard detail={detail}/><section className="grid gap-3 md:grid-cols-5"><VendorStatCard label="Ventes" value={money(s.revenue)}/><VendorStatCard label="Commandes" value={detail.orders.length}/><VendorStatCard label="Panier moyen" value={money(s.averageOrderValue)}/><VendorStatCard label="Retours" value="0" hint="contrat API futur"/><VendorStatCard label="Remboursements" value="0" hint="contrat API futur"/></section>{section==='overview'&&<div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-6"><VendorWalletCard detail={detail}/><VendorAnalyticsChart stats={s}/><VendorCatalogTable products={detail.products.slice(0,8)}/></div><aside className="space-y-6"><VendorTimeline/><VendorPayoutTable/></aside></div>}{section==='profile'&&<VendorProfileCard vendor={detail.vendor}/>} {section==='catalog'&&<><div className="rounded-2xl border p-4 text-sm dark:border-zinc-800">Recherche, filtres persistants, catégories, stock, prix, variantes, publication, brouillon, archive · actions ajouter, modifier, supprimer, dupliquer, exporter.</div><VendorCatalogTable products={detail.products}/></>}{section==='orders'&&<VendorOrdersTable orders={detail.orders}/>} {section==='customers'&&<VendorCustomerTable orders={detail.orders}/>} {section==='analytics'&&<VendorAnalyticsChart stats={s}/>} {section==='wallet'&&<><VendorWalletCard detail={detail}/><VendorTimeline/></>} {section==='payouts'&&<VendorPayoutTable/>} {section==='messaging'&&<VendorMessageCenter/>} {section==='documents'&&<VendorDocumentGrid/>} {section==='settings'&&<div className="rounded-3xl border p-5 dark:border-zinc-800"><h3 className="font-semibold">Paramètres vendeur</h3><p className="text-sm text-zinc-500">Domaine, storefront, taxes, devise, notifications, rôles et préparation Diapay.</p></div>}</div>}
