import React, { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import ProtectedRoute from '@/components/ProtectedRoute';
import { useBackendAuth } from '@/auth/useBackendAuth';
import { fetchClientQuotes } from '@/api/logistics';
import { StatusPill, quoteStatusOptions, labelFor, QUOTE_STATUSES } from '@/components/client/status';
import { amountOf, formatDate, idOf, money, refOf, routeOf } from '@/components/client/format';

const PAGE_SIZE = 10;
const AccountQuotes = () => {
  const { getToken } = useBackendAuth();
  const [quotes, setQuotes] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [page, setPage] = useState(1);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setQuotes(await fetchClientQuotes(await getToken())); } catch (e) { setError(e.message || 'Erreur de chargement des devis.'); } finally { setLoading(false); } }, [getToken]);
  useEffect(() => { load(); }, [load]);
  const filtered = useMemo(() => quotes.filter((q) => { const hay = `${refOf(q, 'DEV')} ${q.origin || ''} ${q.destination || ''} ${q.status || ''}`.toLowerCase(); return (status === 'all' || String(q.status).toLowerCase() === status) && hay.includes(search.toLowerCase()); }), [quotes, search, status]);
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const rows = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  useEffect(() => { setPage(1); }, [search, status]);
  return <ProtectedRoute><main className="dx-dashboard-shell"><div className="dx-dashboard"><header className="dx-dashboard__header"><span className="dx-dashboard__eyebrow">espace client · devis</span><h1 className="dx-dashboard__title">Mes devis</h1><p className="dx-dashboard__subtitle">Recherchez, filtrez et suivez chaque demande de devis DiaExpress.</p><div className="dx-dashboard__actions"><Link className="dx-button dx-button--primary" href="/quote-request">Nouveau devis</Link><Link className="dx-button dx-button--outline" href="/compte/dashboard">Dashboard</Link></div></header><section className="dx-section"><div className="dx-filterbar"><label className="dx-field"><span>Recherche</span><input className="dx-input" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Référence, origine, destination" /></label><label className="dx-field"><span>Statut</span><select className="dx-select" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Tous</option>{quoteStatusOptions.map((s) => <option key={s} value={s}>{labelFor(QUOTE_STATUSES, s)}</option>)}</select></label><button className="dx-button dx-button--ghost" onClick={load} type="button">Actualiser</button></div>{loading && <div className="dx-empty">Chargement des devis…</div>}{error && <div className="dx-empty dx-empty--error">{error}</div>}{!loading && !error && <><div className="dx-table-wrapper dx-desktop-table"><table className="dx-table"><thead><tr><th>Référence</th><th>Date</th><th>Origine</th><th>Destination</th><th>Montant</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{rows.map((q) => { const route = routeOf(q); return <tr key={idOf(q)}><td><strong>{refOf(q, 'DEV')}</strong></td><td>{formatDate(q.createdAt)}</td><td>{route.origin}</td><td>{route.destination}</td><td>{money(amountOf(q), q.currency || 'EUR')}</td><td><StatusPill type="quote" status={q.status} /></td><td><Link className="dx-button dx-button--sm dx-button--outline" href={`/account/quotes/${idOf(q)}`}>Détail</Link></td></tr>; })}</tbody></table></div><div className="dx-grid dx-mobile-cards">{rows.map((q) => { const route = routeOf(q); return <article className="dx-card" key={idOf(q)}><strong>{refOf(q, 'DEV')}</strong><StatusPill type="quote" status={q.status} /><p>{route.origin} → {route.destination}</p><p>{money(amountOf(q), q.currency || 'EUR')} · {formatDate(q.createdAt)}</p><Link className="dx-button dx-button--sm dx-button--outline" href={`/account/quotes/${idOf(q)}`}>Ouvrir</Link></article>; })}</div>{!rows.length && <div className="dx-empty">Aucun devis ne correspond aux critères.</div>}<div className="dx-actions"><button disabled={page <= 1} onClick={() => setPage((p) => p - 1)} className="dx-button dx-button--ghost">Précédent</button><span>Page {page}/{pages}</span><button disabled={page >= pages} onClick={() => setPage((p) => p + 1)} className="dx-button dx-button--ghost">Suivant</button></div></>}</section></div></main></ProtectedRoute>;
};
export default AccountQuotes;
