import React, { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import ProtectedRoute from '@/components/ProtectedRoute';
import { useBackendAuth } from '@/auth/useBackendAuth';
import { fetchShipmentById } from '@/api/logistics';
import { StatusPill, shipmentMilestones, labelFor, SHIPMENT_STATUSES } from '@/components/client/status';
import { formatDateTime, idOf, refOf, routeOf } from '@/components/client/format';

const ShipmentDetail = () => {
  const router = useRouter(); const { id } = router.query; const { getToken } = useBackendAuth(); const [shipment, setShipment] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!id) return; setLoading(true); setError(''); try { setShipment(await fetchShipmentById(id, await getToken())); } catch (e) { setError(e.message || 'Erreur expédition.'); } finally { setLoading(false); } }, [id, getToken]);
  useEffect(() => { load(); }, [load]);
  const history = useMemo(() => shipment?.timeline || shipment?.statusHistory || shipment?.trackingUpdates || shipment?.events || [], [shipment]);
  const index = shipmentMilestones.indexOf(String(shipment?.status || '').toLowerCase());
  return <ProtectedRoute><main className="dx-dashboard-shell"><div className="dx-dashboard"><header className="dx-dashboard__header"><span className="dx-dashboard__eyebrow">détail expédition</span><h1 className="dx-dashboard__title">{shipment ? refOf(shipment, 'TRK') : 'Expédition'}</h1><p className="dx-dashboard__subtitle">Résumé transport, colis et timeline professionnelle.</p><div className="dx-dashboard__actions"><Link href="/account/shipments" className="dx-button dx-button--outline">Retour expéditions</Link>{shipment?.trackingCode && <Link href={`/track-shipment?code=${encodeURIComponent(shipment.trackingCode)}`} className="dx-button dx-button--primary">Tracking public</Link>}</div></header>{loading && <div className="dx-empty">Chargement de l’expédition…</div>}{error && <div className="dx-empty dx-empty--error">{error}</div>}{shipment && <><section className="dx-grid dx-grid--four"><article className="dx-card"><p>Tracking</p><strong>{shipment.trackingCode || shipment.trackingNumber || '—'}</strong></article><article className="dx-card"><p>Statut</p><StatusPill status={shipment.status} /></article><article className="dx-card"><p>Quote liée</p>{shipment.quoteId?._id || shipment.quoteId ? <Link href={`/account/quotes/${shipment.quoteId?._id || shipment.quoteId}`}>Voir le devis</Link> : '—'}</article><article className="dx-card"><p>Dernière MAJ</p><strong>{formatDateTime(shipment.updatedAt)}</strong></article></section><section className="dx-grid dx-grid--two"><article className="dx-card"><h2>Résumé</h2><p>{routeOf(shipment).origin} → {routeOf(shipment).destination}</p><p>Transport: {shipment.transportType || shipment.serviceType || shipment.carrier || '—'}</p><p>Colis: {shipment.packageCount || shipment.packages?.length || shipment.parcels?.length || '—'}</p></article><article className="dx-card"><h2>Informations colis</h2><p>Poids: {shipment.weight || shipment.totalWeight || shipment.quoteId?.weight || '—'} kg</p><p>Volume: {shipment.volume || shipment.totalVolume || shipment.quoteId?.volume || '—'} m³</p><p>Créé: {formatDateTime(shipment.createdAt)}</p></article></section><section className="dx-section"><h2>Timeline</h2><div className="dx-stepper" role="list">{shipmentMilestones.map((step, i) => <div className={`dx-stepper__item ${index >= i ? 'is-active' : ''}`} key={step} role="listitem"><span>{i + 1}</span><div><strong>{labelFor(SHIPMENT_STATUSES, step)}</strong><small>{index >= i ? 'Étape atteinte' : 'À venir'}</small></div></div>)}</div>{history.length ? <ol className="dx-timeline">{history.map((h, i) => <li key={h._id || i}><strong>{labelFor(SHIPMENT_STATUSES, h.status || h.event)}</strong><p>{h.comment || h.note || h.message || 'Mouvement expédition'}</p><small>{formatDateTime(h.timestamp || h.createdAt || h.date)}</small></li>)}</ol> : <div className="dx-empty">Aucun mouvement détaillé disponible.</div>}</section></>}</div></main></ProtectedRoute>;
};
export default ShipmentDetail;
