const providers = [
  { provider: 'mock', type: 'mock', status: 'ready', mode: 'sandbox', configured: true, countries: ['BF','CI','SN','GH','NG'], currencies: ['XOF','USD','EUR','USDC'], methods: ['mock','mobile-money','bank-card','bank-transfer','crypto'], capabilities: ['refund','partial_refund','cancel','webhook','async'] },
  { provider: 'orange_money', type: 'mobile_money', status: 'not_configured', mode: 'live', configured: false, countries: ['BF','CI','SN'], currencies: ['XOF'], methods: ['mobile-money'], capabilities: ['webhook','async','requires_phone'] },
  { provider: 'moov_money', type: 'mobile_money', status: 'not_configured', mode: 'live', configured: false, countries: ['BF','CI','BJ','TG'], currencies: ['XOF'], methods: ['mobile-money'], capabilities: ['webhook','async','requires_phone'] },
  { provider: 'wave', type: 'mobile_money', status: 'not_configured', mode: 'live', configured: false, countries: ['CI','SN'], currencies: ['XOF'], methods: ['mobile-money'], capabilities: ['webhook','async','requires_phone'] },
  { provider: 'stripe', type: 'bank_card', status: 'not_configured', mode: 'live', configured: false, countries: ['US','CI','SN'], currencies: ['USD','EUR','XOF'], methods: ['bank-card'], capabilities: ['webhook','redirect','requires_email'] },
  { provider: 'stablecoin', type: 'crypto', status: 'not_configured', mode: 'live', configured: false, countries: ['US','CI','SN'], currencies: ['USDC'], methods: ['crypto'], capabilities: ['confirmations','compliance_status'] },
];
export default function ProvidersPage() {
  return <main className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wide text-blue-600">Diapay Providers</p><h1 className="text-3xl font-bold text-slate-950">Provider adapter architecture</h1><p className="text-slate-600">Vue de configuration sandbox/live. Le mock est explicite pour les tests; aucun fallback silencieux n'est autorisé en production.</p></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full divide-y divide-slate-200 text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Provider</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Sandbox/live</th><th className="px-4 py-3">Countries</th><th className="px-4 py-3">Currencies</th><th className="px-4 py-3">Methods</th><th className="px-4 py-3">Capabilities</th></tr></thead><tbody className="divide-y divide-slate-100">{providers.map((provider) => <tr key={provider.provider}><td className="px-4 py-3 font-semibold text-slate-900">{provider.provider}</td><td className="px-4 py-3">{provider.type}</td><td className="px-4 py-3"><span className={provider.configured ? 'rounded-full bg-emerald-50 px-2 py-1 text-emerald-700' : 'rounded-full bg-amber-50 px-2 py-1 text-amber-700'}>{provider.status}</span></td><td className="px-4 py-3">{provider.mode}</td><td className="px-4 py-3">{provider.countries.join(', ')}</td><td className="px-4 py-3">{provider.currencies.join(', ')}</td><td className="px-4 py-3">{provider.methods.join(', ')}</td><td className="px-4 py-3">{provider.capabilities.join(', ')}</td></tr>)}</tbody></table></div></main>;
}
