import type { Request, Response } from 'express'; import { assertUrl } from './webhook.validation'; import { createWebhookEndpoint, deleteWebhookEndpoint, getWebhookEndpoint, listWebhookEndpoints, mask, updateWebhookEndpoint } from './webhook-endpoint.repository'; import { listWebhookEvents } from './webhook-event.repository'; import { listWebhookDeliveries } from './webhook-delivery.repository';
const merchant=(req:Request)=> req.header('x-merchant-id') ?? (req.header('authorization')?.startsWith('Bearer sk_') ? req.header('authorization')!.replace(/^Bearer\s+sk_(test|live)_/,'merchant_').slice(0,64) : 'Diapay Sandbox Merchant');
function notFound(res:Response){return res.status(404).json({success:false,message:'Webhook endpoint not found',error:{code:'NOT_FOUND'}})}
export function listEndpoints(req:Request,res:Response){res.json(listWebhookEndpoints(merchant(req)).map((e)=>mask(e)));}
export function createEndpoint(req:Request,res:Response){try{assertUrl(req.body?.url); const ep=createWebhookEndpoint({merchantId:merchant(req),applicationId:req.body.applicationId,url:req.body.url,description:req.body.description,events:Array.isArray(req.body.events)?req.body.events.map(String):undefined}); res.status(201).json({ ...mask(ep,true), note:'Secret is only returned at creation. Store it securely.'});}catch(e){res.status((e as any).status??500).json({success:false,message:(e as Error).message,error:{code:(e as any).code??'API_ERROR'}})}}
export function getEndpoint(req:Request,res:Response){const ep=getWebhookEndpoint(req.params.id); if(!ep||ep.merchantId!==merchant(req))return notFound(res); res.json(mask(ep));}
export function patchEndpoint(req:Request,res:Response){const ep=getWebhookEndpoint(req.params.id); if(!ep||ep.merchantId!==merchant(req))return notFound(res); const updated=updateWebhookEndpoint(ep.id,{url:req.body.url,description:req.body.description,enabled:req.body.enabled,events:req.body.events}); res.json(mask(updated!));}
export function deleteEndpoint(req:Request,res:Response){const ep=getWebhookEndpoint(req.params.id); if(!ep||ep.merchantId!==merchant(req))return notFound(res); deleteWebhookEndpoint(ep.id); res.json({deleted:true,id:ep.id});}
export function listEvents(req:Request,res:Response){res.json(listWebhookEvents(merchant(req)));}
export function listDeliveries(_req:Request,res:Response){res.json(listWebhookDeliveries());}
