'use client';
import Link from 'next/link';
import { useStore } from '@/context/store';
import { Product, Category, Slide, ShippingOption } from '@/lib/types';

export const CurrencySwitcher = () => { const { currency, setCurrency } = useStore(); return <select className='rounded border px-2 py-1' value={currency} onChange={(e)=>setCurrency(e.target.value)}><option>FCFA</option><option>USD</option></select>; };
export const LanguageSwitcher = () => { const { locale, setLocale } = useStore(); return <select className='rounded border px-2 py-1' value={locale} onChange={(e)=>setLocale(e.target.value)}><option value='fr'>FR</option><option value='en'>EN</option><option value='zh'>中文</option></select>; };
export const HeroSlider = ({ slides }: { slides: Slide[] }) => <div className='overflow-hidden rounded-2xl bg-black text-white'>{slides.map(s => <div key={s.id} className='grid gap-4 p-8 md:grid-cols-2'><div><h2 className='text-3xl font-bold'>{s.title}</h2><p>{s.subtitle}</p><Link href='/catalogue' className='mt-4 inline-block rounded bg-amber-400 px-4 py-2 text-black'>{s.cta}</Link></div><img src={s.imageUrl} className='h-56 w-full rounded object-cover' /></div>)}</div>;
export const CategoryCard = ({ category }: { category: Category }) => <div className='rounded-xl bg-white p-3 shadow'><img src={category.imageUrl} className='h-28 w-full rounded object-cover'/><h3 className='mt-2 font-semibold'>{category.name}</h3><p className='text-sm text-slate-500'>{category.productCount} produits</p></div>;
export const ProductCard = ({ product, onAdd }: { product: Product; onAdd: (p: Product)=>void; }) => { const { currency } = useStore(); const price = currency==='USD'? (product.priceFcfa/600).toFixed(2): product.priceFcfa.toLocaleString('fr-FR'); return <div className='rounded-xl bg-white p-3 shadow'><img src={product.images[0]} className='h-40 w-full rounded object-cover'/><h3 className='mt-2 font-semibold'>{product.name}</h3><p className='text-sm'>{price} {currency}</p><div className='mt-2 flex gap-2'><Link href={`/product/${product.id}`} className='rounded border px-2 py-1 text-sm'>Voir</Link><button onClick={()=>onAdd(product)} className='rounded bg-[#556B2F] px-2 py-1 text-sm text-white'>Ajouter</button></div></div>; };
export const CartDrawer = () => { const { cart } = useStore(); return <Link href='/cart' className='rounded bg-black px-3 py-1 text-white'>Panier ({cart.length})</Link>; };
export const CheckoutSummary = ({ shipping = 0 }: { shipping?: number }) => { const { totalFcfa, currency } = useStore(); const total = totalFcfa + shipping; return <div className='rounded-xl bg-white p-4 shadow'><p>Sous-total: {totalFcfa} FCFA</p><p>Livraison: {shipping} FCFA</p><p className='font-bold'>Total: {currency==='USD'?(total/600).toFixed(2)+' USD': total+' FCFA'}</p></div>; };
export const ShippingOptions = ({ options, selected, onSelect }: { options: ShippingOption[]; selected?: string; onSelect: (id: string)=>void; }) => <div className='space-y-2'>{options.map(o => <button key={o.id} onClick={()=>onSelect(o.id)} className={`w-full rounded border p-3 text-left ${selected===o.id?'border-amber-400':''}`}>{o.name} - {o.priceFcfa} FCFA ({o.etaDays})</button>)}</div>;
export const StatusBadge = ({ status }: { status: string }) => <span className='rounded bg-slate-100 px-2 py-1 text-xs'>{status}</span>;
