"use client";
import { useEffect, useMemo, useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import { DataTable } from "@/components/ui/data-table";
import { StatusBadge } from "@/components/ui/status-badge";
import { cmsService } from "@/services/cms-service";

type Currency = { _id: string; code: string; name: string; symbol: string; rateToDefault: number; isActive: boolean; isDefault: boolean; lastUpdatedAt?: string; updatedAt?: string };
const blank = { code: "USD", name: "Dollar américain", symbol: "$", rateToDefault: 1, isActive: true, isDefault: false };
export default function CurrenciesPage() {
  const [items, setItems] = useState<Currency[]>([]); const [form, setForm] = useState<any>(blank); const [editing, setEditing] = useState<string | null>(null); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setItems(await cmsService.getCurrencies() as Currency[]); } catch (e) { setError(e instanceof Error ? e.message : "Chargement impossible"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const save = async () => { if (!form.code || !form.name || !form.symbol || Number(form.rateToDefault) <= 0) { setError("Code, nom, symbole et taux positif sont obligatoires."); return; } setError(""); setMessage("Sauvegarde…"); try { editing ? await cmsService.updateCurrency(editing, form) : await cmsService.createCurrency(form); setForm(blank); setEditing(null); setMessage("Devise sauvegardée."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Sauvegarde impossible"); setMessage(""); } };
  const edit = (c: Currency) => { setEditing(c._id); setForm({ code: c.code, name: c.name, symbol: c.symbol, rateToDefault: c.rateToDefault, isActive: c.isActive, isDefault: c.isDefault }); };
  const patch = async (c: Currency, payload: Partial<Currency>) => { if (!window.confirm("Confirmer la modification de devise ?")) return; await cmsService.updateCurrency(c._id, payload); await load(); };
  const remove = async (c: Currency) => { if (!window.confirm(`Supprimer ${c.code} ?`)) return; try { await cmsService.deleteCurrency(c._id); setMessage("Devise supprimée."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Suppression impossible"); } };
  const filtered = useMemo(() => items.filter(c => `${c.code} ${c.name} ${c.symbol}`.toLowerCase().includes(search.toLowerCase())), [items, search]);
  const rows = filtered.map(c => ({ id: c._id, searchableText: `${c.code} ${c.name}`, cells: [c.code, c.name, c.symbol, c.rateToDefault, <StatusBadge key="s" status={c.isActive ? "active" : "inactive"} />, c.isDefault ? "Oui" : "Non", c.lastUpdatedAt || c.updatedAt ? new Date(c.lastUpdatedAt || c.updatedAt || "").toLocaleString("fr-FR") : "—", <span key="a" className="flex flex-wrap gap-2"><button className="rounded border px-2 py-1" onClick={() => edit(c)}>Modifier</button><button className="rounded border px-2 py-1" onClick={() => patch(c, { isActive: !c.isActive })}>{c.isActive ? "Désactiver" : "Activer"}</button><button className="rounded border px-2 py-1" disabled={c.isDefault} onClick={() => patch(c, { isDefault: true })}>Défaut</button><button className="rounded border px-2 py-1 text-red-700 disabled:opacity-50" disabled={c.isDefault} onClick={() => remove(c)}>Supprimer</button></span>] }));
  return <div className="space-y-6"><PageHeader title="Devises" subtitle="Gestion des taux, statuts et devise par défaut" />{message && <p className="rounded-xl bg-blue-500/10 p-3">{message}</p>}{error && <p className="rounded-xl bg-red-500/10 p-3 text-red-700">{error}</p>}<section className="grid gap-3 rounded-2xl border p-4 md:grid-cols-4 dark:border-zinc-800"><input className="rounded-xl border p-2" placeholder="Recherche" value={search} onChange={e=>setSearch(e.target.value)} /><select className="rounded-xl border p-2" value={form.code} onChange={e=>setForm({...form, code:e.target.value})}>{["XOF","USD","EUR","CAD","CNY"].map(c=><option key={c}>{c}</option>)}</select><input className="rounded-xl border p-2" placeholder="Nom" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="rounded-xl border p-2" placeholder="Symbole" value={form.symbol} onChange={e=>setForm({...form,symbol:e.target.value})}/><input className="rounded-xl border p-2" type="number" step="0.000001" min="0" value={form.rateToDefault} onChange={e=>setForm({...form,rateToDefault:Number(e.target.value)})}/><label className="flex items-center gap-2"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/> Défaut</label><button onClick={save} className="rounded-xl bg-olive-700 p-2 text-white">{editing ? "Sauvegarder" : "Créer"}</button></section>{loading ? <p className="rounded-xl border p-4">Chargement devises…</p> : rows.length ? <DataTable headers={["Code","Nom","Symbole","Taux","Statut","Défaut","Dernière mise à jour","Actions"]} rows={rows} /> : <p className="rounded-xl border p-4 text-sm text-zinc-500">Aucune devise.</p>}</div>;
}
