"use client";

import Link from "next/link";
import type { ReactNode } from "react";
import { useEffect, useState } from "react";
import { cmsApi } from "@/services/cms-api";
import { tokens } from "@/design/tokens";
import type { StorefrontBlock, StorefrontBlockType, StorefrontConfig, StorefrontHomePage } from "@/types/white-label";

type OverviewItem = { vendorId: string; logo?: string; shopName: string; domain: string; status: "published" | "draft" | "pending" | "failed"; updatedAt?: string };
type DomainStatus = "pending" | "verified" | "failed" | "disabled";
const blockTypes: StorefrontBlockType[] = ["hero", "carousel", "featuredProducts", "video", "banners", "collections", "testimonials", "faq", "cta"];
const fallbackConfig: StorefrontConfig = { vendorId: "demo-vendor", shopName: "Aura Luxury", slogan: "Sélection premium inspirée des boutiques Stitch.", logo: "", favicon: "", colors: { primary: tokens.colors.primary, secondary: tokens.colors.primaryDark, accent: tokens.colors.accent, background: tokens.colors.background, text: tokens.colors.text }, fonts: { heading: tokens.typography.fontDisplay, body: tokens.typography.fontAdmin }, buttons: { radius: tokens.radius.pill, style: "solid" }, socialLinks: { instagram: "@auraluxury", tiktok: "@auraluxury" } };
const fallbackBlocks: StorefrontBlock[] = [
  { id: "hero", type: "hero", title: "Nouvelle collection privée", enabled: true, settings: { subtitle: "Maison Aura Luxury", cta: "Découvrir", description: "Une vitrine boutique premium inspirée des références Stitch aura_luxury." } },
  { id: "carousel", type: "carousel", title: "Sélections éditoriales", enabled: true, settings: { description: "Mise en avant des lancements et campagnes saisonnières." } },
  { id: "featured", type: "featuredProducts", title: "Produits signatures", enabled: true },
  { id: "collections", type: "collections", title: "Collections privées", enabled: true },
  { id: "cta", type: "cta", title: "Créer une expérience boutique", enabled: true },
];
function card(c = "") { return `rounded-2xl border border-brand-border bg-brand-surface shadow-sm ${c}`; }
function unwrap<T>(r: any, fallback: T): T { return r?.data ?? r ?? fallback; }
function StateCard({ title, text }: { title: string; text: string }) { return <div className={card("p-8 text-center")}><h2 className="text-xl font-semibold text-brand-dark">{title}</h2><p className="mt-2 text-sm text-brand-muted">{text}</p></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-2 text-sm font-medium text-brand-dark"><span>{label}</span>{children}</label>; }
const input = "rounded-xl border border-brand-border bg-white px-3 py-2 text-sm outline-none focus:border-brand-primary";

export function StorefrontOverviewTable() {
  const [items, setItems] = useState<OverviewItem[]>([]); const [status, setStatus] = useState("all"); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { cmsApi.vendors().then((r:any) => { const vendors = unwrap<any[]>(r, []); setItems(vendors.map((v:any) => ({ vendorId: String(v._id ?? v.id), logo: v.logo, shopName: v.shopName ?? v.businessName ?? "Boutique vendeur", domain: v.storefrontDomain ?? `${(v.shopName ?? v.businessName ?? "boutique").toLowerCase().replace(/\s+/g,"-")}.diamarket.store`, status: v.storefrontStatus ?? (v.status === "active" ? "published" : "draft"), updatedAt: v.updatedAt ?? v.createdAt }))); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  const filtered = items.filter(i => (status === "all" || i.status === status) && `${i.shopName} ${i.domain}`.toLowerCase().includes(query.toLowerCase()));
  if (loading) return <StateCard title="Chargement des boutiques" text="Synchronisation des vendeurs et configurations storefront…" />; if (error) return <StateCard title="Configuration indisponible" text={`Endpoint /vendors ou /storefront indisponible : ${error}`} />;
  return <section className="space-y-5"><div className={card("p-5")}><div className="flex flex-col gap-3 md:flex-row"><input className={input + " flex-1"} placeholder="Rechercher une boutique, un domaine…" value={query} onChange={e=>setQuery(e.target.value)} /><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tous statuts</option><option value="published">Publié</option><option value="draft">Brouillon</option><option value="pending">Pending</option><option value="failed">Erreur</option></select></div></div>{filtered.length === 0 ? <StateCard title="Aucune boutique" text="Aucun vendeur ne correspond aux filtres." /> : <div className="overflow-x-auto rounded-2xl border border-brand-border bg-white"><table className="min-w-[900px] w-full text-sm"><thead className="bg-brand-surface-alt text-left text-xs uppercase tracking-widest text-brand-muted"><tr><th className="p-4">Boutique</th><th>Domaine</th><th>Publication</th><th>Dernière modification</th><th className="text-right pr-4">Actions</th></tr></thead><tbody>{filtered.map(i=><tr key={i.vendorId} className="border-t border-brand-border"><td className="p-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-brand-surface-alt font-semibold text-brand-primary">{i.logo ? <img src={i.logo} alt="" className="h-full w-full rounded-xl object-cover"/> : i.shopName.slice(0,2)}</div><b>{i.shopName}</b></div></td><td>{i.domain}</td><td><span className="rounded-full bg-brand-surface-alt px-3 py-1 text-xs text-brand-primary">{i.status}</span></td><td>{i.updatedAt ? new Date(i.updatedAt).toLocaleDateString("fr-FR") : "—"}</td><td className="space-x-2 pr-4 text-right">{["brand-kit","builder","domain","preview"].map(a=><Link key={a} className="rounded-full border border-brand-border px-3 py-1 hover:bg-brand-surface-alt" href={`/storefront/${i.vendorId}/${a}`}>{a === "brand-kit" ? "Brand Kit" : a[0].toUpperCase()+a.slice(1)}</Link>)}</td></tr>)}</tbody></table></div>}</section>;
}
export function BrandColorPicker({ label, value, onChange }: { label:string; value:string; onChange:(v:string)=>void }) { return <Field label={label}><div className="flex gap-2"><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-12"/><input className={input+" flex-1"} value={value} onChange={e=>onChange(e.target.value)} /></div></Field>; }
export function FontPicker({ label, value, onChange }: { label:string; value:string; onChange:(v:string)=>void }) { return <Field label={label}><select className={input} value={value} onChange={e=>onChange(e.target.value)}><option>{tokens.typography.fontDisplay}</option><option>{tokens.typography.fontAdmin}</option><option>Georgia, serif</option><option>Arial, sans-serif</option></select></Field>; }
export function StorefrontPreview({ config=fallbackConfig, blocks=fallbackBlocks }: { config?: StorefrontConfig; blocks?: StorefrontBlock[] }) { const active = blocks.filter(b=>b.enabled); return <aside className={card("overflow-hidden")} style={{fontFamily: config.fonts?.body, color: config.colors?.text}}><div className="p-5" style={{background: config.colors?.background}}><div className="flex items-center justify-between"><b style={{fontFamily: config.fonts?.heading}}>{config.shopName}</b><span className="rounded-full px-3 py-1 text-xs text-white" style={{background: config.colors?.primary}}>Live</span></div><div className="mt-6 rounded-2xl p-6 text-white" style={{background: `linear-gradient(135deg, ${config.colors?.secondary}, ${config.colors?.primary})`}}><p className="text-xs uppercase tracking-widest">Storefront preview</p><h3 className="mt-2 text-3xl font-semibold" style={{fontFamily: config.fonts?.heading}}>{config.slogan}</h3><button className="mt-5 rounded-full px-4 py-2 text-sm" style={{background: config.colors?.accent}}>Explorer</button></div><div className="mt-4 grid gap-3">{active.map(b=><div key={b.id} className="rounded-xl bg-white p-4 shadow-sm"><span className="text-xs uppercase text-brand-muted">{b.type}</span><h4 className="font-semibold">{b.title}</h4></div>)}</div></div></aside>; }
export function BrandKitForm({ vendorId }: { vendorId: string }) { const [config,setConfig]=useState(fallbackConfig); useEffect(()=>{cmsApi.storefrontConfig(vendorId).then((r:any)=>setConfig({...fallbackConfig,...unwrap(r,{})})).catch(()=>{})},[vendorId]); const set=(p:Partial<StorefrontConfig>)=>setConfig(c=>({...c,...p})); return <div className="grid gap-6 lg:grid-cols-[1fr_420px]"><form className={card("grid gap-4 p-5")} onSubmit={e=>{e.preventDefault(); cmsApi.updateStorefrontConfig(vendorId, config).catch(()=>{});}}><Field label="Logo"><input className={input} value={config.logo??""} onChange={e=>set({logo:e.target.value})}/></Field><Field label="Favicon"><input className={input} value={config.favicon??""} onChange={e=>set({favicon:e.target.value})}/></Field><Field label="Nom boutique"><input className={input} value={config.shopName} onChange={e=>set({shopName:e.target.value})}/></Field><Field label="Slogan"><textarea className={input} value={config.slogan??""} onChange={e=>set({slogan:e.target.value})}/></Field><div className="grid gap-4 md:grid-cols-3"><BrandColorPicker label="Primaire" value={config.colors.primary} onChange={v=>set({colors:{...config.colors,primary:v}})}/><BrandColorPicker label="Secondaire" value={config.colors.secondary} onChange={v=>set({colors:{...config.colors,secondary:v}})}/><BrandColorPicker label="Accent" value={config.colors.accent??tokens.colors.accent} onChange={v=>set({colors:{...config.colors,accent:v}})}/></div><FontPicker label="Police titre" value={config.fonts.heading} onChange={v=>set({fonts:{...config.fonts,heading:v}})}/><FontPicker label="Police body" value={config.fonts.body} onChange={v=>set({fonts:{...config.fonts,body:v}})}/><Field label="Style bouton"><select className={input} value={config.buttons?.style} onChange={e=>set({buttons:{...config.buttons,style:e.target.value as any}})}><option value="solid">Solid</option><option value="soft">Soft</option><option value="outline">Outline</option></select></Field><Field label="Réseaux sociaux"><textarea className={input} value={Object.entries(config.socialLinks??{}).map(([k,v])=>`${k}: ${v}`).join("\n")} onChange={e=>set({socialLinks:Object.fromEntries(e.target.value.split("\n").map(line=>line.split(":").map(part=>part.trim())).filter(parts=>parts[0]).map(([key,...rest])=>[key,rest.join(":")]))})} placeholder={"instagram: @boutique\ntiktok: @boutique"} /></Field><button className="rounded-full bg-brand-primary px-5 py-3 text-white">Enregistrer</button></form><StorefrontPreview config={config}/></div>; }
export function BlockList({ blocks, setBlocks }: { blocks: StorefrontBlock[]; setBlocks:(b:StorefrontBlock[])=>void }) { const move=(i:number,d:number)=>{const n=[...blocks]; const [x]=n.splice(i,1); n.splice(Math.max(0,Math.min(n.length,i+d)),0,x); setBlocks(n)}; const update=(id:string, patch:Partial<StorefrontBlock>)=>setBlocks(blocks.map(x=>x.id===id?{...x,...patch}:x)); return <div className="grid gap-3">{blocks.map((b,i)=><div key={b.id} className="grid gap-3 rounded-xl border border-brand-border p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-xs uppercase text-brand-muted">{b.type}</span><h3 className="font-semibold">{b.title}</h3></div><div className="flex flex-wrap gap-2 text-sm"><button onClick={()=>update(b.id,{enabled:!b.enabled})}>{b.enabled?"Désactiver":"Activer"}</button><button onClick={()=>move(i,-1)}>↑</button><button onClick={()=>move(i,1)}>↓</button><button onClick={()=>setBlocks([...blocks,{...b,id:`${b.id}-copy-${Date.now()}`,title:`${b.title ?? b.type} copie`}])}>Dupliquer</button><button className="text-red-700" onClick={()=>setBlocks(blocks.filter(x=>x.id!==b.id))}>Supprimer</button></div></div><div className="grid gap-2 md:grid-cols-2"><input className={input} value={b.title??""} onChange={e=>update(b.id,{title:e.target.value})} placeholder="Titre du bloc"/><input className={input} value={String(b.settings?.description??"")} onChange={e=>update(b.id,{settings:{...(b.settings??{}),description:e.target.value}})} placeholder="Description / paramètre rapide"/></div></div>)}</div>; }
export function BlockForm({ blocks, setBlocks }: { blocks: StorefrontBlock[]; setBlocks:(b:StorefrontBlock[])=>void }) { const [type,setType]=useState<StorefrontBlockType>("hero"); return <div className="flex gap-2"><select className={input} value={type} onChange={e=>setType(e.target.value as StorefrontBlockType)}>{blockTypes.map(t=><option key={t} value={t}>{t}</option>)}</select><button className="rounded-full bg-brand-primary px-4 py-2 text-white" onClick={()=>setBlocks([...blocks,{id:`${type}-${Date.now()}`,type,title:type,enabled:true}])}>Ajouter bloc</button></div>; }
export function BlockEditor({ vendorId }: { vendorId: string }) { const [blocks,setBlocks]=useState(fallbackBlocks); useEffect(()=>{cmsApi.storefrontHome(vendorId).then((r:any)=>setBlocks(unwrap<StorefrontHomePage>(r,{vendorId,blocks:fallbackBlocks}).blocks??fallbackBlocks)).catch(()=>{})},[vendorId]); return <div className="grid gap-6 lg:grid-cols-[1fr_420px]"><section className={card("space-y-4 p-5")}><BlockForm blocks={blocks} setBlocks={setBlocks}/><BlockList blocks={blocks} setBlocks={setBlocks}/><button className="rounded-full bg-brand-dark px-5 py-3 text-white" onClick={()=>cmsApi.updateStorefrontHome(vendorId,{blocks}).catch(()=>{})}>Enregistrer la page</button></section><StorefrontPreview blocks={blocks}/></div>; }
export function DomainStatusCard({ status="pending" }: { status?: DomainStatus }) { const tone={pending:"bg-brand-surface-alt text-brand-primary",verified:"bg-emerald-50 text-emerald-700",failed:"bg-red-50 text-red-700",disabled:"bg-slate-100 text-slate-600"}[status]; return <div className={card("p-5")}><p className="text-sm text-brand-muted">Statut DNS</p><strong className={`mt-3 inline-flex rounded-full px-3 py-1 ${tone}`}>{status}</strong>{status==="failed"&&<p className="mt-3 text-sm text-red-700">Le CNAME ne pointe pas encore vers storefront.diamarket.com.</p>}</div>; }
export function DnsInstructionsCard() { return <div className={card("p-5")}><h2 className="text-lg font-semibold">Instructions CNAME</h2><p className="mt-2 text-sm text-brand-muted">Créez un enregistrement CNAME vers <code>storefront.diamarket.com</code>, puis lancez la vérification.</p></div>; }
export function DomainManager({ vendorId }: { vendorId: string }) { const [domain,setDomain]=useState(""); const [status,setStatus]=useState<DomainStatus>("pending"); return <div className="grid gap-6 lg:grid-cols-3"><div className={card("space-y-4 p-5 lg:col-span-2")}><Field label="Sous-domaine Diamarket"><input className={input} value={`${vendorId}.diamarket.store`} readOnly /></Field><Field label="Domaine personnalisé"><input className={input} value={domain} onChange={e=>setDomain(e.target.value)} placeholder="boutique.example.com" /></Field><button className="rounded-full bg-brand-primary px-5 py-3 text-white" onClick={()=>cmsApi.connectDomain(vendorId,{domain}).then(()=>setStatus("pending")).catch(()=>setStatus("failed"))}>Vérifier</button></div><DomainStatusCard status={status}/><div className="lg:col-span-3"><DnsInstructionsCard/></div></div>; }
export function StorefrontCmsPreview({ vendorId }: { vendorId: string }) { const [config,setConfig]=useState(fallbackConfig); const [blocks,setBlocks]=useState(fallbackBlocks); useEffect(()=>{cmsApi.storefrontConfig(vendorId).then((r:any)=>setConfig({...fallbackConfig,...unwrap(r,{})})).catch(()=>{}); cmsApi.storefrontHome(vendorId).then((r:any)=>setBlocks(unwrap<StorefrontHomePage>(r,{vendorId,blocks:fallbackBlocks}).blocks??fallbackBlocks)).catch(()=>{})},[vendorId]); return <StorefrontPreview config={config} blocks={blocks}/>; }
