import { Router } from 'express';
import { Request } from 'express';
import { categoriesController } from '../controllers/categories.controller';
import { ordersController } from '../controllers/orders.controller';
import { paymentsController } from '../controllers/payments.controller';
import { productsController } from '../controllers/products.controller';
import { projectsController } from '../controllers/projects.controller';
import { mediaController } from '../controllers/media.controller';
import { vendorRequestsController } from '../controllers/vendor-requests.controller';
import { requireAuth } from '../middlewares/requireAuth';
import { requireRole } from '../middlewares/requireRole';
import { requirePermission } from '../middlewares/requirePermission';
import { ownershipGuard } from '../middlewares/ownershipGuard';
import { validateRequest } from '../middlewares/validate-request.middleware';
import { localImageUpload } from '../middlewares/local-upload.middleware';
import { authRouter } from './auth.routes';
import { requireCmsRole } from '../middlewares/requireCmsRole';

const validateProduct = (req: Request) => {
  const required = ['name', 'slug', 'description', 'price', 'currency', 'category', 'vendor', 'stock'];
  for (const field of required) if (req.body[field] === undefined) return `Missing field: ${field}`;
  return null;
};
const validateProject = (req: Request) => (!req.body.title || !String(req.body.title).trim() ? 'title is required' : null);
const validateCategory = (req: Request) => (!req.body.name || !req.body.slug ? 'name and slug are required' : null);
const validateVendorRequest = (req: Request) => (!req.body.businessName ? 'businessName is required' : null);
const validateOrder = (req: Request) => {
  const required = ['customer', 'vendor', 'items', 'totalAmount'];
  for (const field of required) if (req.body[field] === undefined) return `Missing field: ${field}`;
  if (!Array.isArray(req.body.items) || req.body.items.length === 0) return 'items must be a non-empty array';
  return null;
};

export const apiRouter = Router();
apiRouter.use('/v1/auth', authRouter);
apiRouter.use('/auth', authRouter);
apiRouter.get('/health', (_req, res) => res.json({ ok: true }));
apiRouter.get('/products', productsController.list);
apiRouter.get('/products/:slug', productsController.getBySlug);
apiRouter.post('/products', requireAuth, requireCmsRole, requirePermission('products:create'), ownershipGuard('product'), validateRequest(validateProduct), productsController.create);
apiRouter.put('/products/:id', requireAuth, requireCmsRole, requirePermission('products:update'), productsController.update);
apiRouter.delete('/products/:id', requireAuth, requireCmsRole, requirePermission('products:delete'), productsController.remove);
apiRouter.get('/projects', projectsController.list);
apiRouter.get('/projects/:id', projectsController.getById);
apiRouter.post('/projects', requireAuth, requireCmsRole, requirePermission('projects:create'), validateRequest(validateProject), projectsController.create);
apiRouter.put('/projects/:id', requireAuth, requireCmsRole, requirePermission('projects:update'), projectsController.update);
apiRouter.delete('/projects/:id', requireAuth, requireCmsRole, requirePermission('projects:delete'), projectsController.remove);
apiRouter.get('/media', mediaController.list);
apiRouter.post('/media/url', requireAuth, requireCmsRole, requirePermission('media:manage'), mediaController.createFromUrl);
apiRouter.post('/media/upload', requireAuth, requireCmsRole, requirePermission('media:manage'), localImageUpload, mediaController.upload);
apiRouter.put('/media/:id', requireAuth, requireCmsRole, requirePermission('media:manage'), mediaController.update);
apiRouter.delete('/media/:id', requireAuth, requireCmsRole, requirePermission('media:manage'), mediaController.remove);
apiRouter.get('/categories', categoriesController.list);
apiRouter.post('/categories', requireAuth, requireCmsRole, validateRequest(validateCategory), categoriesController.create);
apiRouter.put('/categories/:id', requireAuth, requireCmsRole, categoriesController.update);
apiRouter.delete('/categories/:id', requireAuth, requireCmsRole, categoriesController.remove);
apiRouter.post('/vendor-requests', requireAuth, validateRequest(validateVendorRequest), vendorRequestsController.create);
apiRouter.get('/vendor-requests', requireAuth, requirePermission('vendors:approve'), vendorRequestsController.list);
apiRouter.put('/vendor-requests/:id/approve', requireAuth, requirePermission('vendors:approve'), vendorRequestsController.approve);
apiRouter.put('/vendor-requests/:id/reject', requireAuth, requirePermission('vendors:approve'), vendorRequestsController.reject);
apiRouter.post('/orders', requireAuth, ownershipGuard('order'), validateRequest(validateOrder), ordersController.create);
apiRouter.get('/orders', requireAuth, requirePermission('orders:read'), ordersController.list);
apiRouter.get('/orders/:id', requireAuth, requirePermission('orders:read'), ordersController.getById);
apiRouter.get('/orders/:id/payment-status', requireAuth, ordersController.getPaymentStatus);
apiRouter.put('/orders/:id/status', requireAuth, requirePermission('orders:update'), ordersController.updateStatus);
apiRouter.post('/payments/diapay/checkout-session', requireAuth, paymentsController.createDiapayCheckoutSession);
apiRouter.get('/payments/diapay/session/:sessionId', requireAuth, paymentsController.retrieveDiapaySession);
apiRouter.post('/payments/diapay/webhook', paymentsController.handleDiapayWebhook);
apiRouter.post('/orders/:id/shipment/sync', requireAuth, requireRole('admin', 'super_admin', 'agent_logistique', 'marketplace_point_focal'), ordersController.syncShipmentStatus);
