const curl = `curl -X POST http://localhost:5100/api/v1/checkout/sessions \\
  -H "Authorization: Bearer sk_test_***" \\
  -H "Idempotency-Key: order_1001" \\
  -H "Content-Type: application/json" \\
  -d '{"amount":25000,"currency":"XOF","successUrl":"https://shop.test/success","cancelUrl":"https://shop.test/cancel"}'`;
const fetchJs = `const response = await fetch('/api/v1/checkout/sessions', { method: 'POST', headers: { Authorization: 'Bearer sk_test_***', 'Content-Type': 'application/json' }, body: JSON.stringify({ amount: 25000, currency: 'XOF', successUrl, cancelUrl }) });`;
const nodeSdk = `const diapay = new Diapay({ secretKey: process.env.DIAPAY_SECRET_KEY });\nconst session = await diapay.checkout.sessions.create({ amount: 25000, currency: 'XOF', successUrl, cancelUrl });`;
const express = `app.post('/webhooks/diapay', express.raw({ type: 'application/json' }), diapay.webhooks.expressWebhookMiddleware({ secret: process.env.DIAPAY_WEBHOOK_SECRET, handler: async (event) => { if (event.type === 'payment.paid') markOrderPaid(event.data.object.metadata.orderId); } }));`;
const next = `export async function POST(req) { const rawBody = await req.text(); const event = Diapay.constructWebhookEvent(rawBody, req.headers.get('diapay-signature'), process.env.DIAPAY_WEBHOOK_SECRET); return Response.json({ received: true, type: event.type }); }`;
function Code({children}:{children:string}){return <pre><code>{children}</code></pre>}
export default function Quickstart(){return <main className="portal"><section className="content"><h1>Diapay Quickstart</h1><ol><li>Create an application in the dashboard.</li><li>Create a masked test API key; store only the secret in server env.</li><li>Create a checkout session.</li><li>Redirect the customer to <code>checkoutUrl</code>.</li><li>Receive <code>payment.paid</code>.</li><li>Verify the HMAC webhook signature.</li><li>Display the order as paid after your database update succeeds.</li></ol><h2>curl</h2><Code>{curl}</Code><h2>JavaScript fetch</h2><Code>{fetchJs}</Code><h2>Node SDK</h2><Code>{nodeSdk}</Code><h2>Express webhook handler</h2><Code>{express}</Code><h2>Next.js route handler</h2><Code>{next}</Code><p>Common pitfalls: never expose <code>sk_</code> keys, use idempotency keys, do not trust redirects without webhooks, and keep Mobile Money operators in sandbox/mock mode until real credentials are configured.</p></section></main>}
