const Quote = require('../models/Quote');
const QuoteAuditLog = require('../models/QuoteAuditLog');
const mongoose = require('mongoose');
const { push: notify } = require('../services/notificationService');
const { ensureRequestIdentity } = require('../services/diaexpressAuthService');
const { ApiError } = require('../utils/http');
const { createShipmentFromQuote } = require('../services/shipmentService');
const { normalizeQuoteStatus } = require('../src/domain/statuses');
const { assertValidTransition, buildLifecyclePatch, toCanonicalQuote } = require('../services/quoteDomainService');
const hooks = require('../src/lib/events/quoteWorkflowHooks');

const resolveIdentity = (req) => req.identity || ensureRequestIdentity(req);
const roleOf = (req) => String(req.user?.role || req.identity?.role || req.identity?.type || 'admin').toLowerCase();
const can = (req, action) => {
  const role = roleOf(req);
  if (role === 'admin') return true;
  if (role === 'manager') return ['read','write','validate','convert'].includes(action);
  if (['operations','operator','ops'].includes(role)) return ['read','write','convert'].includes(action);
  return action === 'read';
};
const requirePermission = (req, action) => { if (!can(req, action)) throw new ApiError(403, 'QUOTE_PERMISSION_DENIED', 'Permission insuffisante pour cette action'); };
const actor = (req) => { const i=resolveIdentity(req)||{}; return { userId: i.principalId || req.user?._id?.toString?.() || null, userLabel: i.label || req.user?.email || null, role: roleOf(req) }; };
const audit = async (quote, req, action, oldValue, newValue, comment) => {
  try {
    await QuoteAuditLog.create({ quoteId: quote._id, ...actor(req), action, oldValue, newValue, comment });
  } catch (_error) {
    // Audit persistence must not break the operational workflow in test/offline modes.
  }
};
const history = (quote, req, action, fromStatus, toStatus, note, metadata) => { const a=actor(req); quote.reviewHistory = Array.isArray(quote.reviewHistory)?quote.reviewHistory:[]; quote.reviewHistory.push({ action, fromStatus, toStatus, actorId:a.userId, actorLabel:a.userLabel, role:a.role, note: note || null, metadata: metadata || null, at:new Date() }); };
const sendUserQuoteNotification = async (quote, title, message) => { if (!quote.userId) return; await notify({ userId: quote.userId, type:'quote', title, message, entity:{ entityType:'Quote', entityId:quote._id }, channels:{ inApp:true } }); };

exports.listAll = async (req, res) => { try { requirePermission(req,'read'); const q={}; ['status','transportType','origin','destination','userEmail'].forEach(k=>{ if(req.query[k]) q[k]=k==='status'?normalizeQuoteStatus(req.query[k]):new RegExp(String(req.query[k]),'i'); }); const text = String(req.query.search || req.query.reference || '').trim(); if (text) { const terms = [{ userEmail:new RegExp(text,'i') },{ recipientContactName:new RegExp(text,'i') },{ recipientContactEmail:new RegExp(text,'i') },{ requestedByLabel:new RegExp(text,'i') },{ requestedBy:new RegExp(text,'i') },{ origin:new RegExp(text,'i') },{ destination:new RegExp(text,'i') },{ trackingNumber:new RegExp(text,'i') }]; if (mongoose.Types.ObjectId.isValid(text)) terms.unshift({ _id: text }); q.$or = terms; } if (req.query.client) { const clientTerms = [{ userEmail:new RegExp(req.query.client,'i') },{ recipientContactName:new RegExp(req.query.client,'i') },{ recipientContactEmail:new RegExp(req.query.client,'i') },{ requestedByLabel:new RegExp(req.query.client,'i') }]; q.$and = [...(q.$and || []), { $or: clientTerms }]; } if (req.query.from || req.query.to) q.createdAt = { ...(req.query.from && {$gte:new Date(req.query.from)}), ...(req.query.to && {$lte:new Date(req.query.to)}) }; const items=await Quote.find(q).sort({createdAt:-1}).limit(Math.min(Number(req.query.limit)||250,500)); res.json({ quotes: items.map(toCanonicalQuote), permissions: { read:true, modification:can(req,'write'), validation:can(req,'validate'), conversion:can(req,'convert') } }); } catch(e){ const s=e instanceof ApiError?e.status:500; res.status(s).json({message:e.message, code:e.code}); } };
exports.getOne = async (req,res)=>{ try{ requirePermission(req,'read'); const q=await Quote.findById(req.params.id); if(!q) return res.status(404).json({message:'Quote non trouvé'}); const logs=await QuoteAuditLog.find({quoteId:q._id}).sort({createdAt:1}); res.json({ quote: toCanonicalQuote(q), auditLogs: logs }); } catch(e){ const s=e instanceof ApiError?e.status:500; res.status(s).json({message:e.message, code:e.code}); } };

exports.updateByAdmin = async (req,res)=>{ try{ requirePermission(req,'write'); const q=await Quote.findById(req.params.id); if(!q) return res.status(404).json({message:'Quote non trouvé'}); const before={ finalPrice:q.finalPrice, currency:q.currency, notes:q.notes, adminNotes:q.adminNotes, pricingNote:q.pricingNote }; ['finalPrice','currency','notes','adminNotes','reviewNotes','pricingNote','priority','carrier','productType','productLocation','contactPhone'].forEach(k=>{ if(req.body[k]!==undefined) q[k]=req.body[k]; }); if (req.body.finalPrice!==undefined && !req.body.overrideReason) throw new ApiError(400,'QUOTE_OVERRIDE_REASON_REQUIRED','Une raison est obligatoire pour override price'); if (req.body.finalPrice!==undefined) history(q,req,'price_overridden',q.status,q.status,req.body.overrideReason,{ oldPrice: before.finalPrice, newPrice: q.finalPrice }); else history(q,req,'admin_note_updated',q.status,q.status,req.body.notes || req.body.adminNotes); await q.save(); await audit(q,req, req.body.finalPrice!==undefined?'price_overridden':'admin_update', before, { finalPrice:q.finalPrice,currency:q.currency,notes:q.notes,adminNotes:q.adminNotes,pricingNote:q.pricingNote }, req.body.overrideReason || req.body.notes); res.json({quote:toCanonicalQuote(q)}); } catch(e){ const s=e instanceof ApiError?e.status:500; res.status(s).json({message:e.message, code:e.code}); } };
const transition = async (req,res,to,opts={})=>{ requirePermission(req, opts.permission||'write'); const q=await Quote.findById(req.params.id); if(!q) return res.status(404).json({message:'Quote non trouvé'}); const from=q.status; const next=assertValidTransition(q.status,to); const patch=buildLifecyclePatch({status:next, actorId:actor(req).userId, actorLabel:actor(req).userLabel, role:actor(req).role, note:opts.note(req), reason:opts.reason?.(req), metadata:opts.metadata?.(req)}); const {reviewHistoryEntry,...fields}=patch; q.set(fields); if(reviewHistoryEntry){ reviewHistoryEntry.fromStatus=from; q.reviewHistory=[...(q.reviewHistory||[]),reviewHistoryEntry]; } opts.apply?.(q,req); await q.save(); await audit(q,req,opts.action||'status_transition',{status:from},{status:next},opts.note(req)); await opts.hook?.({quoteId:q._id, status:next, actor:actor(req), message:opts.note(req)}); await opts.notify?.(q); return res.json({quote:toCanonicalQuote(q)}); };
exports.markUnderReview=(req,res)=>transition(req,res,'under_review',{action:'review_started',note:r=>r.body?.note||'Revue admin démarrée'}).catch(e=>res.status(e.status||500).json({message:e.message,code:e.code}));
exports.markReadyForShipment=(req,res)=>transition(req,res,'converted_to_shipment',{action:'ready_for_shipment_legacy',note:r=>r.body?.note||'Legacy ready-for-shipment rejected by canonical workflow'}).catch(e=>res.status(e.status||500).json({message:e.message,code:e.code}));
exports.patchStatus=(req,res)=>transition(req,res,req.body.status,{action:'status_changed',note:r=>r.body?.note||r.body?.comment||'Statut modifié',reason:r=>r.body?.reason}).catch(e=>res.status(e.status||500).json({message:e.message,code:e.code}));
exports.requestMoreInfo=(req,res)=>transition(req,res,'info_requested',{action:'info_requested',note:r=>r.body?.message||r.body?.note||'Informations complémentaires demandées',apply:(q,r)=>{q.reviewNotes=r.body?.message||r.body?.note||q.reviewNotes;},hook:hooks.QuoteInfoRequested,notify:q=>sendUserQuoteNotification(q,'Informations demandées',`Votre devis #${q._id} nécessite des informations complémentaires.`)}).catch(e=>res.status(e.status||500).json({message:e.message,code:e.code}));
exports.approve=async(req,res)=>{ try{ requirePermission(req,'validate'); const q=await Quote.findById(req.params.id); if(!q) return res.status(404).json({message:'Quote non trouvé'}); const from=q.status; if(req.body?.finalPrice!==undefined) q.finalPrice=req.body.finalPrice; if(req.body?.currency) q.currency=req.body.currency; const nowNote=req.body?.note||'Quote approved by admin'; const steps=[]; let current=normalizeQuoteStatus(q.status); if(current==='submitted'){ steps.push('under_review','priced','approved'); } else if(current==='under_review'){ steps.push('priced','approved'); } else if(current==='info_requested'){ steps.push('under_review','priced','approved'); } else { steps.push('approved'); } for (const step of steps){ const next=assertValidTransition(current,step); const patch=buildLifecyclePatch({status:next, actorId:actor(req).userId, actorLabel:actor(req).userLabel, role:actor(req).role, note: next==='approved'?nowNote:'Transition automatique avant approbation'}); const {reviewHistoryEntry,...fields}=patch; q.set(fields); if(reviewHistoryEntry){ reviewHistoryEntry.fromStatus=current; q.reviewHistory=[...(q.reviewHistory||[]),reviewHistoryEntry]; } current=next; } await q.save(); await audit(q,req,'approved',{status:from},{status:q.status, finalPrice:q.finalPrice, currency:q.currency},nowNote); await hooks.QuoteApproved({quoteId:q._id,status:q.status,actor:actor(req)}); await sendUserQuoteNotification(q,'Devis approuvé',`Votre devis #${q._id} a été approuvé.`); res.json({quote:toCanonicalQuote(q)}); } catch(e){res.status(e.status||500).json({message:e.message,code:e.code});} };
exports.reject=async(req,res)=>{ try{ if(!req.body?.reason) return res.status(400).json({message:'Commentaire obligatoire pour rejet',code:'QUOTE_REJECTION_REASON_REQUIRED'}); requirePermission(req,'validate'); const q=await Quote.findById(req.params.id); if(!q) return res.status(404).json({message:'Quote non trouvé'}); const from=q.status; let current=normalizeQuoteStatus(q.status); const steps=current==='submitted'?['under_review','rejected']:current==='info_requested'?['under_review','rejected']:['rejected']; for(const step of steps){ const next=assertValidTransition(current,step); const patch=buildLifecyclePatch({status:next,actorId:actor(req).userId,actorLabel:actor(req).userLabel,role:actor(req).role,note: step==='rejected'?req.body.reason:'Transition automatique avant refus',reason:req.body.reason}); const {reviewHistoryEntry,...fields}=patch; q.set(fields); if(reviewHistoryEntry){ reviewHistoryEntry.fromStatus=current; q.reviewHistory=[...(q.reviewHistory||[]),reviewHistoryEntry]; } current=next; } await q.save(); await audit(q,req,'rejected',{status:from},{status:q.status,reason:req.body.reason},req.body.reason); await hooks.QuoteRejected({quoteId:q._id,status:q.status,actor:actor(req),reason:req.body.reason}); await sendUserQuoteNotification(q,'Devis refusé',`Votre devis #${q._id} a été refusé.`); res.json({quote:toCanonicalQuote(q)}); } catch(e){res.status(e.status||500).json({message:e.message,code:e.code});} };
exports.convert=async(req,res)=>{ try{ requirePermission(req,'convert'); const q=await Quote.findById(req.params.id); if(!q) return res.status(404).json({message:'Quote non trouvé'}); if(normalizeQuoteStatus(q.status)!=='approved') throw new ApiError(409,'QUOTE_NOT_ELIGIBLE_FOR_SHIPMENT','Quote not eligible for shipment conversion');
    if(q.shipmentId) throw new ApiError(409,'QUOTE_ALREADY_CONVERTED','Quote already converted to shipment'); const before={status:q.status,shipmentId:q.shipmentId}; const result=await createShipmentFromQuote({quoteId:q._id, identity:resolveIdentity(req)||{}, notes:req.body?.note}); await audit(result.quote,req,'converted_to_shipment',before,{status:result.quote.status,shipmentId:result.shipment._id,trackingCode:result.shipment.trackingCode},req.body?.note); await hooks.QuoteConverted({quoteId:q._id, shipmentId:result.shipment._id, trackingCode:result.shipment.trackingCode, actor:actor(req)}); res.json({success:true, shipment:result.shipment, quote:toCanonicalQuote(result.quote)}); } catch(e){ res.status(e.status||500).json({success:false,message:e.message,code:e.code}); } };
exports.dashboard=async(req,res)=>{ try{ requirePermission(req,'read'); const agg=await Quote.aggregate([{ $group:{ _id:'$status', count:{ $sum:1 } } }]); const by=Object.fromEntries(agg.map(i=>[normalizeQuoteStatus(i._id),i.count])); res.json({ pending:by.submitted||0, toReview:(by.under_review||0)+(by.info_requested||0), approved:by.approved||0, converted:by.converted_to_shipment||0 }); } catch(e){res.status(e.status||500).json({message:e.message,code:e.code});} };
exports.dispatch=exports.convert; exports.updateTracking=async(req,res)=>res.status(410).json({message:'Tracking lives on Shipment flow',code:'QUOTE_TRACKING_DEPRECATED'});
