const Shipment = require('../models/Shipment');
const ShipmentDocument = require('../models/ShipmentDocument');
const { ApiError, success } = require('../utils/http');
const { identityHasRole, ensureRequestIdentity } = require('../services/diaexpressAuthService');
const allowedMime = ['application/pdf','image/jpeg','image/png','image/webp','text/plain'];
async function getShipment(req) { const shipment = await Shipment.findById(req.params.id || req.params.shipmentId); if (!shipment) throw new ApiError(404,'SHIPMENT_NOT_FOUND','Shipment introuvable'); return shipment; }
function sanitize(doc, isAdmin=false) { const o = doc.toObject ? doc.toObject() : doc; if (!isAdmin && o.proof) { delete o.proof.deliveryCode; if (o.type === 'delivery_proof') delete o.proof.signature; } return o; }
exports.adminList = async (req,res,next)=>{ try{ const s=await getShipment(req); const docs=await ShipmentDocument.find({ shipmentId:s._id }).sort({createdAt:-1}); return success(res, docs.map(d=>sanitize(d,true)), { legacy:{documents:docs} }); }catch(e){next(e);} };
exports.clientList = async (req,res,next)=>{ try{ const identity=ensureRequestIdentity(req); const s=await getShipment(req); if(!identityHasRole(identity,'admin') && s.principalId !== identity?.principalId) throw new ApiError(403,'FORBIDDEN','Accès non autorisé'); const isAdmin=identityHasRole(identity,'admin'); const docs=await ShipmentDocument.find(isAdmin ? { shipmentId:s._id } : { shipmentId:s._id, visibility:'client_visible' }).sort({createdAt:-1}); return success(res, docs.map(d=>sanitize(d,isAdmin)), { legacy:{documents:docs} }); }catch(e){next(e);} };
exports.publicList = async (req,res,next)=>{ try{ const s=await Shipment.findOne({ trackingCode:req.params.trackingCode }); if(!s) throw new ApiError(404,'SHIPMENT_NOT_FOUND','Shipment introuvable'); const docs=await ShipmentDocument.find({ shipmentId:s._id, visibility:'public_tracking' }).select('-proof.signature -proof.deliveryCode -recipientEmail -recipientPhone'); return success(res, docs.map(d=>sanitize(d,false)), { legacy:{documents:docs} }); }catch(e){next(e);} };
exports.upload = async (req,res,next)=>{ try{ const s=await getShipment(req); const b=req.body||{}; if(!b.fileUrl) throw new ApiError(400,'VALIDATION_ERROR','fileUrl requis'); if(b.mimeType && !allowedMime.includes(b.mimeType)) throw new ApiError(400,'INVALID_FILE_TYPE','Type fichier non autorisé'); if(Number(b.size||0) > 10*1024*1024) throw new ApiError(400,'FILE_TOO_LARGE','Fichier trop volumineux'); const doc=await ShipmentDocument.create({ shipmentId:s._id, quoteId:s.quoteId, type:b.type||'other', title:b.title||'Document', fileUrl:b.fileUrl, mimeType:b.mimeType, size:b.size, visibility:b.visibility||'admin_only', uploadedBy:req.identity?.principalId||req.user?._id?.toString() }); return success(res, sanitize(doc,true), {status:201, legacy:{document:doc}}); }catch(e){next(e);} };
exports.remove = async (req,res,next)=>{ try{ const s=await getShipment(req); const deleted=await ShipmentDocument.findOneAndDelete({_id:req.params.documentId, shipmentId:s._id}); if(!deleted) throw new ApiError(404,'DOCUMENT_NOT_FOUND','Document introuvable'); return success(res,{deleted:true}); }catch(e){next(e);} };
async function proof(req,res,next,type){ try{ const s=await getShipment(req); const b=req.body||{}; const doc=await ShipmentDocument.create({ shipmentId:s._id, quoteId:s.quoteId, type, title:type==='pickup_proof'?'Preuve de collecte':'Preuve de livraison', fileUrl:b.photo||b.signature||'proof://metadata-only', mimeType:b.photoMimeType||'application/json', visibility:b.visibility||'admin_only', uploadedBy:req.identity?.principalId||req.user?._id?.toString(), proof:{ photo:b.photo, signature:b.signature, recipientName:b.recipientName, deliveryCode:b.deliveryCode, agent:b.agent, date:b.date||new Date(), location:b.location, note:b.note } }); return success(res, sanitize(doc,true), {status:201, legacy:{document:doc}}); }catch(e){next(e);} }
exports.proofPickup=(req,res,next)=>proof(req,res,next,'pickup_proof');
exports.proofDelivery=(req,res,next)=>proof(req,res,next,'delivery_proof');
